version: '3.8'

services:
  rust:
    build:
      context: ../../
      dockerfile: ./docker/rust/Dockerfile
      args:
        WORKING_DIRECTORY: ${WORKING_DIRECTORY}
    tty: true
    working_dir: "/${WORKING_DIRECTORY}"
    volumes:
      - ../../:/${WORKING_DIRECTORY}
      - rust-target:/workspace/target
    # Fix slow shutdown of web container
    init: true

    # For jupyter-notebook
    environment:
      - TZ=Asia/Tokyo
      - JUPYTER_PORT=${JUPYTER_PORT}
    ports:
      - ${JUPYTER_PORT}:${JUPYTER_PORT}
    command: >
      bash -c "
        jupyter notebook --no-browser --ip=0.0.0.0 --port ${JUPYTER_PORT} --allow-root --NotebookApp.token='demo'
      "

volumes:
  rust-target:
